url: 'https://beautifulwebtype.com'

plugins:
  - jekyll-sitemap

include: ['.well-known']
exclude: ['Rakefile']

collections:
  typefaces:
    output: true
    permalink: /:name/
  glyphs:
    output: true
    permalink: /:name/glyphs/
  samples:
    output: false
  pairings:
    output: false

defaults:
  - # Set default layouts
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'typefaces'
    values:
      layout: 'detail'
  -
    scope:
      path: ''
      type: 'glyphs'
    values:
      layout: 'glyphs'
  -
    scope:
      path: ''
      type: 'samples'
    values:
      layout: 'none'
  -
    scope:
      path: 'categories'
      type: 'pages'
    values:
      layout: 'category'
  - # Set default body classes for type detail pages
    scope:
      path: '_typefaces/display'
      type: 'typefaces'
    values:
      body-class: 'display detail'
  -
    scope:
      path: '_typefaces/monospaced'
      type: 'typefaces'
    values:
      body-class: 'monospaced detail'
  -
    scope:
      path: '_typefaces/sans-serif'
      type: 'typefaces'
    values:
      body-class: 'sans-serif detail'
  -
    scope:
      path: '_typefaces/serif'
      type: 'typefaces'
    values:
      body-class: 'serif detail'
  - # Set default body classes for glyph explorer pages
    scope:
      path: '_glyphs/display'
      type: 'glyphs'
    values:
      body-class: 'display glyphs'
  -
    scope:
      path: '_glyphs/monospaced'
      type: 'glyphs'
    values:
      body-class: 'monospaced glyphs'
  -
    scope:
      path: '_glyphs/sans-serif'
      type: 'glyphs'
    values:
      body-class: 'sans-serif glyphs'
  -
    scope:
      path: '_glyphs/serif'
      type: 'glyphs'
    values:
      body-class: 'serif glyphs'
